###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   06/10/2020
#   @package        :   Integrations
#   @description    :   All the Integrations 
###############################################################################

# Google Calendar
# google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_client_secret

# Testing internet speedtest  
# speedtestdotnet:

# gdacs:
#   categories:
#     - Earthquake
#     - Tropical Cyclone
#   radius: 500
#   latitude: !secret MY_LATITUDE
#   longitude: !secret MY_LONGITUDE

# TPLink / KASA - Hardcoding the IP Address - REMOVED in 2023.7
# tplink:
#   discovery: false
#   switch:
#     - host: 192.168.7.105
#     - host: 192.168.7.107
#     - host: 192.168.7.116
#     - host: 192.168.7.120
#     - host: 192.168.7.136
#     - host: 192.168.7.137

# WZYE Devices - Using the HACS integration
# wyzeapi:
#   username: !secret wyze_user
#   password: !secret wyze_password

# IFTTT (May be removed - I dont think I am using this.)
ifttt:
  key: !secret IFTTT_API_KEY 

# # Using the HACS Daily Snapshot Clean Up Plugin 
# clean_up_snapshots_service:
#   host: !secret snapshot_url
#   token: !secret snapshot_token
#   number_of_snapshots_to_keep: 3

binary_sensor:
  - platform: flic
