homeassistant:
  external_url: !secret ahsl_base_url
  internal_url: http://192.168.7.187:8123
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages
  media_dirs:
    haunted_sounds: /media/haunted_sounds
    music: /media/music
    sounds: /media/sounds
    disney: /media/disney
    books: /media/books
    images: /media/images

#config for pyscript
pyscript:
  allow_all_imports: true
  hass_is_global: true
#config for lovelace dash
lovelace:
  mode: storage
  dashboards:
    lovelace-roomsense:
      mode: yaml
      title: RoomSense IQ
      icon: mdi:script
      show_in_sidebar: true
      filename: dashboards.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  # ssl_certificate: !secret ahsl_ssl_cert
  # ssl_key: !secret ahsl_ssl_key
  use_x_forwarded_for: true
  trusted_proxies: !secret proxy_ips
  ip_ban_enabled: false
  login_attempts_threshold: 5

ssdp:

zeroconf:

system_health:

mobile_app:

person:

frontend:
  themes: !include_dir_merge_named themes

cloud:

conversation:

device_tracker:
  - platform: eero_tracker
    consider_home: 300
    interval_seconds: 60
    only_macs: "68:54:fd:29:20:87, 68:54:fd:d5:ae:3d, 50:dc:e7:5b:10:69, 2c:cc:44:bf:9b:b4, 28:18:78:74:79:10, 44:61:32:f8:c8:09, 64:cf:d9:3c:5d:0c, 50:02:91:ed:2c:47, ec:71:db:31:0e:6c, 4e:6d:02:24:ac:87, 7c:1c:4e:2e:62:30, dc:03:98:3e:a9:6d, 9E:3E:65:49:38:2A"

# discovery:



sun:

python_script:

map:

zha:
  enable_quirks: true
  custom_quirks_path: /config/zha_quirks

 

binary_sensor:
# - platform: workday
#   country: US
#   province: GA
#   workdays: [mon, tue, wed, thu, fri]
# - platform: workday
#   name: jeff_workday
#   country: US
#   province: GA
#   workdays: [mon, tue, wed, thu, fri]
# Times Of Day
- platform: tod
  name: Night
  after: sunset
  before: sunrise
- platform: tod
  name: Day
  after: sunrise
  before: sunset
- platform: tod
  name: Quiet time
  after: '22:00'
  before: '05:30'
- platform: tod
  name: Lights Out
  after: '23:00'
  before: '05:30'
- platform: tod
  name: Morning
  after: '05:30'
  before: '08:30'
- platform: tod
  name: Evening
  after: '17:00'
  before: '21:00'
- platform: tod
  name: Overnight
  after: '18:00'
  before: '05:30'

### Includes ###
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
mqtt: !include mqtt.yaml
group: !include groups.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
zone: !include zones.yaml
template: !include template.yaml

shell_command:
  google_token: sed -i -e 's/2client.client"}2client.client"}/2client.client"}/g' /config/.google.token

